### ISSUE TITLE
requestLayout() Improperly Called

### ISSUE THREAD

**Issue by nvoigt** [iovation/launchkey-android-authenticator-sdk#9]
When an auth request is being handled and the authorization fragment appears on screen with the Pin Pad security factor I see the following warnings in the logs. Functionality appears to be unaffected but it is quite a lot of WARN level messages for a secure authorization step. This is occurring on a Nexus 5 running 6.0.1. I have not tested to see if this occurs with other security factors.

`W/Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
W/View: requestLayout() improperly called by com.launchkey.android.whitelabel.sdk.ui.PinPadKey{8cc6a97 V.E...C.. ......ID 15,15-187,186 #7f0f0191 app:id/pp_button_1} during layout: running second layout pass
W/View: requestLayout() improperly called by com.launchkey.android.whitelabel.sdk.ui.PinPadKey{f4d9484 V.E...C.. ......ID 217,15-389,186 #7f0f0192 app:id/pp_button_2} during layout: running second layout pass
W/View: requestLayout() improperly called by com.launchkey.android.whitelabel.sdk.ui.PinPadKey{960a46d V.E...C.. ......ID 419,15-591,186 #7f0f0193 app:id/pp_button_3} during layout: running second layout pass
W/View: requestLayout() improperly called by com.launchkey.android.whitelabel.sdk.ui.PinPadKey{98d68a2 V.E...C.. ......ID 15,15-187,187 #7f0f0194 app:id/pp_button_4} during layout: running second layout pass
W/View: requestLayout() improperly called by com.launchkey.android.whitelabel.sdk.ui.PinPadKey{6631933 V.E...C.. ......ID 217,15-389,187 #7f0f0195 app:id/pp_button_5} during layout: running second layout pass
W/View: requestLayout() improperly called by com.launchkey.android.whitelabel.sdk.ui.PinPadKey{a5174f0 V.E...C.. ......ID 419,15-591,187 #7f0f0196 app:id/pp_button_6} during layout: running second layout pass
W/View: requestLayout() improperly called by com.launchkey.android.whitelabel.sdk.ui.PinPadKey{7f01a69 V.E...C.. ......ID 15,15-187,187 #7f0f0197 app:id/pp_button_7} during layout: running second layout pass
W/View: requestLayout() improperly called by com.launchkey.android.whitelabel.sdk.ui.PinPadKey{f7d6cee V.E...C.. ......ID 217,15-389,187 #7f0f0198 app:id/pp_button_8} during layout: running second layout pass
W/View: requestLayout() improperly called by com.launchkey.android.whitelabel.sdk.ui.PinPadKey{dac158f V.E...C.. ......ID 419,15-591,187 #7f0f0199 app:id/pp_button_9} during layout: running second layout pass
W/View: requestLayout() improperly called by com.launchkey.android.whitelabel.sdk.ui.PinPadKey{c70f01c V.E...C.. ......ID 217,15-389,187 #7f0f019c app:id/pp_button_0} during layout: running second layout pass
W/View: requestLayout() improperly called by android.widget.FrameLayout{6e6f425 V.E...CL. ......ID 15,15-187,187 #7f0f019a app:id/pp_imagebutton_delete_frame} during layout: running second layout pass
W/View: requestLayout() improperly called by android.widget.FrameLayout{85769fa V.E...C.. ......ID 419,15-591,187 #7f0f019d app:id/pp_imagebutton_check_frame} during layout: running second layout pass
W/View: requestLayout() improperly called by com.launchkey.android.whitelabel.sdk.ui.AutoResizeTextView{4872787 V.ED..... ........ 0,14-142,84 #7f0f019f app:id/pinpadkey_text_number} during second layout pass: posting in next frame
W/View: requestLayout() improperly called by com.launchkey.android.whitelabel.sdk.ui.AutoResizeTextView{50126b4 V.ED..... ........ 0,14-142,84 #7f0f019f app:id/pinpadkey_text_number} during second layout pass: posting in next frame
W/View: requestLayout() improperly called by com.launchkey.android.whitelabel.sdk.ui.AutoResizeTextView{e8082dd V.ED..... ........ 0,84-142,126 #7f0f01a0 app:id/pinpadkey_text_label} during second layout pass: posting in next frame
W/View: requestLayout() improperly called by com.launchkey.android.whitelabel.sdk.ui.AutoResizeTextView{8853e52 V.ED..... ........ 0,14-142,84 #7f0f019f app:id/pinpadkey_text_number} during second layout pass: posting in next frame
W/View: requestLayout() improperly called by com.launchkey.android.whitelabel.sdk.ui.AutoResizeTextView{f24b523 V.ED..... ........ 0,84-142,126 #7f0f01a0 app:id/pinpadkey_text_label} during second layout pass: posting in next frame
W/View: requestLayout() improperly called by com.launchkey.android.whitelabel.sdk.ui.AutoResizeTextView{de3fa20 V.ED..... ........ 0,14-142,85 #7f0f019f app:id/pinpadkey_text_number} during second layout pass: posting in next frame
W/View: requestLayout() improperly called by com.launchkey.android.whitelabel.sdk.ui.AutoResizeTextView{5076fd9 V.ED..... ........ 0,85-142,127 #7f0f01a0 app:id/pinpadkey_text_label} during second layout pass: posting in next frame
W/View: requestLayout() improperly called by com.launchkey.android.whitelabel.sdk.ui.AutoResizeTextView{314ed9e V.ED..... ........ 0,14-142,85 #7f0f019f app:id/pinpadkey_text_number} during second layout pass: posting in next frame
W/View: requestLayout() improperly called by com.launchkey.android.whitelabel.sdk.ui.AutoResizeTextView{683807f V.ED..... ........ 0,85-142,127 #7f0f01a0 app:id/pinpadkey_text_label} during second layout pass: posting in next frame
W/View: requestLayout() improperly called by com.launchkey.android.whitelabel.sdk.ui.AutoResizeTextView{85e984c V.ED..... ........ 0,14-142,85 #7f0f019f app:id/pinpadkey_text_number} during second layout pass: posting in next frame
W/View: requestLayout() improperly called by com.launchkey.android.whitelabel.sdk.ui.AutoResizeTextView{9763095 V.ED..... ........ 0,85-142,127 #7f0f01a0 app:id/pinpadkey_text_label} during second layout pass: posting in next frame
W/View: requestLayout() improperly called by com.launchkey.android.whitelabel.sdk.ui.AutoResizeTextView{25e45aa V.ED..... ........ 0,14-142,85 #7f0f019f app:id/pinpadkey_text_number} during second layout pass: posting in next frame
W/View: requestLayout() improperly called by com.launchkey.android.whitelabel.sdk.ui.AutoResizeTextView{6d9a59b V.ED..... ........ 0,85-142,127 #7f0f01a0 app:id/pinpadkey_text_label} during second layout pass: posting in next frame
W/View: requestLayout() improperly called by com.launchkey.android.whitelabel.sdk.ui.AutoResizeTextView{c02ed38 V.ED..... ........ 0,14-142,85 #7f0f019f app:id/pinpadkey_text_number} during second layout pass: posting in next frame
W/View: requestLayout() improperly called by com.launchkey.android.whitelabel.sdk.ui.AutoResizeTextView{2d64111 V.ED..... ........ 0,85-142,127 #7f0f01a0 app:id/pinpadkey_text_label} during second layout pass: posting in next frame
W/View: requestLayout() improperly called by com.launchkey.android.whitelabel.sdk.ui.AutoResizeTextView{1331276 V.ED..... ........ 0,14-142,85 #7f0f019f app:id/pinpadkey_text_number} during second layout pass: posting in next frame
W/View: requestLayout() improperly called by com.launchkey.android.whitelabel.sdk.ui.AutoResizeTextView{fa30077 V.ED..... ........ 0,85-142,127 #7f0f01a0 app:id/pinpadkey_text_label} during second layout pass: posting in next frame
W/View: requestLayout() improperly called by com.launchkey.android.whitelabel.sdk.ui.AutoResizeTextView{595a4e4 V.ED..... ........ 0,14-142,85 #7f0f019f app:id/pinpadkey_text_number} during second layout pass: posting in next frame
`

**Comment by arjleon** [comment]
Thanks for feedback, we'll be checking this out.

**Comment by arjleon** [comment]
PIN Code view has been reworked to help tackle these by flattening the layout as much as possible. I'll leave open and tie to a future milestone.
